### ISSUE TITLE
issue whit initisation

### ISSUE THREAD

**Issue by tibiaforlive** [GustavoBlaze/kingdom-bot#1]
i added it in the client but i keep getting the error every time
VV
ERROR: failed to create widget from style 'NodeImage': 'NodeImage' is not a defined style
ERROR: Unable to load module 'kingdom_bot': LUA ERROR:
/kingdom-bot-master/modules/looting/looting.lua:3: module '/kingdom-bot/data/items.lua' not found:
    no module '/kingdom-bot/data/items.lua'
    no field package.preload['/kingdom-bot/data/items.lua']
    no file '.\/kingdom-bot/data/items\lua.lua'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\lua\/kingdom-bot/data/items\lua.lua'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\lua\/kingdom-bot/data/items\lua\init.lua'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\/kingdom-bot/data/items\lua.lua'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\/kingdom-bot/data/items\lua\init.lua'
    no file '.\/kingdom-bot/data/items\lua.dll'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\/kingdom-bot/data/items\lua.dll'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\loadall.dll'
    no file '.\/kingdom-bot/data/items.dll'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\/kingdom-bot/data/items.dll'
    no file 'D:\Users\Diego\Desktop\Nieuwe map\New-age\Our Custom Client (HotKeys)\loadall.dll'
    unable to open file '/kingdom-bot/data/items.lua': Het systeem kan het opgegeven pad niet vinden.
stack traceback:
    [C]: ?
    [C]: in function 'require'
    /kingdom-bot-master/modules/looting/looting.lua:3: in main chunk
    [C]: in function 'dofile'
    /kingdom-bot-master/kingdombot.lua:3: in main chunk
    [C]: in function 'autoLoadModules'
    /init.lua:49: in main chunk
/\ /\
the issue is like he doen't find the files but them there i looked all of the files are in the maps, i'm new to Lua programming but idk

**Comment by GustavoBlaze** [comment]
You got this error cause you're using a custom client and the bot isn't into the folder called "mods". Try to create a folder "mods" and move the bot folder into

**Comment by tibiaforlive** [comment]
it is in the map called "mods" i used to use bendols candy bot -- this one also needed to be in the map...
i tryed difrent otclient "maybe it was to custom" but no.. i tryed to add it into 9 diffrent ot client  only of of them didn't have the map "mods" so i made this map and tryed it..


it just doesn't work 
i even tryed to put the bot into the "module map" (this was like attempt 30 or so)

**Comment by GustavoBlaze** [comment]
solved
