### ISSUE TITLE
Não esta funcionando

### ISSUE THREAD

**Issue by duzin321** [GustavoBlaze/kingdom-bot#2]
Já Coloquei na pasta MODS.

ERROR: Unable to load module 'kingdom_bot': LUA ERROR:
/kingdom-bot-master/modules/looting/looting.lua:3: module '/kingdom-bot/data/items.lua' not found:
    no module '/kingdom-bot/data/items.lua'
    no field package.preload['/kingdom-bot/data/items.lua']
    no file '.\/kingdom-bot/data/items\lua.lua'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\lua\/kingdom-bot/data/items\lua.lua'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\lua\/kingdom-bot/data/items\lua\init.lua'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\/kingdom-bot/data/items\lua.lua'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\/kingdom-bot/data/items\lua\init.lua'
    no file '.\/kingdom-bot/data/items\lua.dll'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\/kingdom-bot/data/items\lua.dll'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\loadall.dll'
    no file '.\/kingdom-bot/data/items.dll'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\/kingdom-bot/data/items.dll'
    no file 'C:\Users\eduar\OneDrive\Área de Trabalho\OT CLIENT\loadall.dll'
    unable to open file '/kingdom-bot/data/items.lua': O sistema nÃ£o pode encontrar o caminho especificado.
stack traceback:
    [C]: ?
    [C]: in function 'require'
    /kingdom-bot-master/modules/looting/looting.lua:3: in main chunk
    [C]: in function 'dofile'
    /kingdom-bot-master/kingdombot.lua:3: in main chunk
    [C]: in function 'autoLoadModules'
    /init.lua:49: in main chunk

**Comment by GustavoBlaze** [comment]
resolvido
